{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "import nltk\n",
    "from nltk.tokenize import sent_tokenize\n",
    "from urllib import request\n",
    "from bs4 import BeautifulSoup\n",
    "import csv\n",
    "import re\n",
    "\n",
    "\n",
    "def writeToFile(author,doc, id):\n",
    "    i=0\n",
    "    file = open('train1.csv', 'a',newline='',encoding='utf-8')\n",
    "    writer = csv.writer(file,quoting=csv.QUOTE_ALL)\n",
    "    for i, token in enumerate(doc):\n",
    "        writer.writerow([i+id,token,author])\n",
    "    file.close()\n",
    "    return i+id+1;\n",
    "        \n",
    "def getSentences(url, beginning, ending):\n",
    "    response = request.urlopen(url)\n",
    "    text1 = response.read().decode('utf8')\n",
    "    start = text1.find(beginning)\n",
    "    end = text1.find(ending)\n",
    "    text1 = text1[start:end]\n",
    "    text = BeautifulSoup(text1, 'html').get_text()\n",
    "    text=re.sub(r'\\s+', ' ', text)\n",
    "    sentences = sent_tokenize(text)\n",
    "    return sentences\n",
    "\n",
    "id = 0;\n",
    "file = open('train1.csv', 'a',newline='',encoding='utf-8')\n",
    "writer = csv.writer(file,quoting=csv.QUOTE_ALL)\n",
    "writer.writerow([\"ID\",\"Text\",\"Author\"])\n",
    "file.close()\n",
    "#Jonas Biliunas: Kliudziau\n",
    "url = \"http://antologija.lt/text/jonas-biliunas-liudna-pasaka/13\"\n",
    "sentences = getSentences(url, \"Tat buvo nedidelė\", \"1905.V.22\");\n",
    "id = writeToFile(\"Biliunas\",sentences,id)\n",
    "#Jonas Biliunas: Laimes ziburys\n",
    "url = \"http://antologija.lt/text/jonas-biliunas-liudna-pasaka/12\"\n",
    "sentences = getSentences(url,\"Ant aukšto stataus kalno\",\"Ciurichas, 1905.IV.15\");\n",
    "id = writeToFile(\"Biliunas\",sentences,id)\n",
    "#Jonas Biliunas: Ubagas\n",
    "url = \"http://antologija.lt/text/jonas-biliunas-liudna-pasaka/18\"\n",
    "sentences = getSentences(url,\"Parvažiavęs iš užusienių Lietuvon\",\"Niūronys, 1906.VI.8\");\n",
    "id = writeToFile(\"Biliunas\",sentences,id)\n",
    "#Jonas Biliunas: Nemunu\n",
    "url = \"http://antologija.lt/text/jonas-biliunas-liudna-pasaka/09\"\n",
    "sentences = getSentences(url,\"Vienodai ir nuobodžiai čiuksėdama\",\"Ciurichas, 1905.IV.2\");\n",
    "id = writeToFile(\"Biliunas\",sentences,id)\n",
    "#Jonas Biliunas: Lazda\n",
    "url = \"http://antologija.lt/text/jonas-biliunas-liudna-pasaka/17\"\n",
    "sentences = getSentences(url,\"Dabar gimtasai mano sodžius\",\"Guli jinai ant lentynos klėty, ir niekas jos neliečia.\");\n",
    "id = writeToFile(\"Biliunas\",sentences,id)\n",
    "#Kristijonas Donelaitis: Metai - Pavasario linksmybes\n",
    "url = \"http://antologija.lt/text/kristijonas-donelaitis-metai\"\n",
    "sentences = getSentences(url, \"Jau saulelė vėl atkopdama\", \"Gana\");\n",
    "id = writeToFile(\"Donelaitis\",sentences,id)\n",
    "#Kristijonas Donelaitis: Metai - Vasaros darbai\n",
    "url = \"http://antologija.lt/text/kristijonas-donelaitis-metai/2\"\n",
    "sentences = getSentences(url, \",,Sveiks, svieteli margs!\", \"Gana\");\n",
    "#Kristijonas Donelaitis: Metai - Rudenio gėrybės\n",
    "url = \"http://antologija.lt/text/kristijonas-donelaitis-metai/3\"\n",
    "sentences = getSentences(url, \"Ant saulelė vėl nuo\", \"Grečną zopostėlį mums dar pasilikusį matom?\");\n",
    "id = writeToFile(\"Donelaitis\",sentences,id)\n",
    "#Zemaite: Laimė nutekėjimo - Neturėjo geros motynos\n",
    "url = \"http://antologija.lt/text/zemaite-laime-nutekejimo/1\"\n",
    "sentences = getSentences(url, \"Per keletą varstų nuo sodos\", \"1895 m.\");\n",
    "id = writeToFile(\"Zemaite\",sentences,id)\n",
    "#Zemaite: Laimė nutekėjimo - Tofylis\n",
    "url = \"http://antologija.lt/text/zemaite-laime-nutekejimo/10\"\n",
    "sentences = getSentences(url, \"Dabar Zosė jau linksma, užganėdyta\", \"1897 m.\");\n",
    "id = writeToFile(\"Zemaite\",sentences,id)\n",
    "#Zemaite: Laimė nutekėjimo - Sutkai\n",
    "url = \"http://antologija.lt/text/zemaite-laime-nutekejimo/11\"\n",
    "sentences = getSentences(url, \"Pavasarelyj gražus ir tykus oras\", \"Eikim, sutems mumis.\");\n",
    "id = writeToFile(\"Zemaite\",sentences,id)\n",
    "#Zemaite: Laimė nutekėjimo - Sučiuptas velnias\n",
    "url = \"http://antologija.lt/text/zemaite-laime-nutekejimo/14\"\n",
    "sentences = getSentences(url, \"Kad speigas, tai speigas!\", \"1898 m.\");\n",
    "id = writeToFile(\"Zemaite\",sentences,id)\n",
    "#Zemaite: Laimė nutekėjimo - Marti\n",
    "url = \"http://antologija.lt/text/zemaite-laime-nutekejimo/2\"\n",
    "sentences = getSentences(url, \"Besitaisant, besibrūzdant\", \"Man mat nepakelti!..\");\n",
    "id = writeToFile(\"Zemaite\",sentences,id)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
